### ISSUE TITLE
docs: Notifier app link broken

### ISSUE THREAD

**Issue by oscard0m** [gr2m/release-notifier-action#60]
When trying to access to the following link I get a 404. I guess users not owning the app are not allowed to see the page, right?
- https://github.com/settings/installations/12807923

---

Maybe this link can be used? https://github.com/apps/octokit-release-notifier

**Comment by gr2m** [comment]
> I guess users not owning the app are not allowed to see the page, right

right 👍🏼 thanks for opening the issue

> Maybe this link can be used? https://github.com/apps/octokit-release-notifier

could you send a PR and update the URL to this: https://github.com/apps/release-notifier-release-notifier
